world:
- world
messagenight: '&f&l[&c&lBloody Night&f&l] &bDrop items on death, Be Careful!'
messageday: '&f&l[&e&lSunrise&f&l] &bKeep items on death.'
messagekeepnight: '&f&l[&f&lNight&f&l] &bKeep items on death.'
chance: 0.5 # From 0.0 to 1.0. i.e: 0.5=50%