################################################################################
# - Author: HSGamer
# - Some instrutions:
# + "chance" : the chance to have a bloody night, from 0.0 to 1.0 (e.g. 0.5 = 50%)
# + if you want to disable messages, just leave them empty (e.g. actionbar: '')
################################################################################
## Vietnamese Messages config
# night:
#     message: '&f&l[&c&lĐêm của Quỷ&f&l] &bChết mất đồ, hãy cẩn thận!'
#     title:
#         title: '&c&lĐÊM CỦA QUỶ'
#         subtitle: '&eChết mất đồ, Hãy cẩn thận!!'
#     actionbar: ''
# keepnight:
#     message: '&f&l[&f&lĐêm của Chúa&f&l] &bChết không mất đồ.'
#     title:
#         title: '&b&lĐÊM CỦA CHÚA'
#         subtitle: '&eChết không mất đồ'
#     actionbar: ''
# day:
#     message: '&f&l[&e&lBan ngày&f&l] &bChết không mất đồ.'
#     title:
#         title: '&d&lBAN NGÀY'
#         subtitle: '&eChết không mất đồ'
#     actionbar: ''
################################################################################
world:
- world
chance: 0.5
night:
    message: '&f&l[&c&lBloody Night&f&l] &bDrop items on death, Be Careful!'
    title:
        title: '&c&lBLOODY NIGHT'
        subtitle: '&eDrop items on death, Be Careful!'
    actionbar: ''
keepnight:
    message: '&f&l[&f&lNight&f&l] &bKeep items on death.'
    title:
        title: '&b&lNIGHT'
        subtitle: '&eKeep items on death'
    actionbar: ''
day:
    message: '&f&l[&e&lSunrise&f&l] &bKeep items on death.'
    title:
        title: '&d&lSUNRISE'
        subtitle: '&eKeep items on death'
    actionbar: ''