name: NonKeepNightChance
author: HSGamer
version: 2.0
main: me.HSGamer.NKNC.NKNC
depend: [MagicTitles]
softdepend: [DeathDropsAPI]
commands:
 nonkeepnightchance:
  usage: /<command>
  descripsion: Reload
  permission: nknc.reload
  aliases: [nknc, nkncreload, nonkeepnightchancereload]