name: NonKeepNightChance
author: HSGamer
version: 1.1
main: me.HSGamer.NKNC.NKNC
softdepend: [DeathDropsAPI]
commands:
 nonkeepnightchance:
  usage: /<command>
  descripsion: Reload
  permission: nknc.reload
  aliases: [nknc, nkncreload, nonkeepnightchancereload]