name: NonKeepNightChance
author: HSGamer
version: 3.0
main: me.HSGamer.NKNC.NKNC
depend: [BountifulAPI]
commands:
 nonkeepnightchance:
  usage: /<command>
  descripsion: Reload
  permission: nknc.reload
  aliases: [nknc, nkncreload, nonkeepnightchancereload]