name: NonKeepNightChance
author: HSGamer
version: 1.0
main: me.HSGamer.NKNC.NKNC
softdepand: [DeathDropsAPI]
commands:
 nonkeepnightchance:
  usage: /<command>
  descripsion: Reload
  permission: nknc.reload
  aliases: [nknc, nkncreload, nonkeepnightchancereload]